### PR TITLE
[JENKINS-72161] avoid inodes check takes agents online

### PR DESCRIPTION
**Pull request by mawinter69**
also JENKINS-72160

Use an OfflineCause specific to the Inodes usage when taking an agent offline and check before taking an agent online if the current cause is an Inodes cause. If not it wasn't the plugin that took the agent offline, thus it needs to stay offline.

Use the cause as data object so we can highlight the table cell when agent is offline. This will also show a tooltip with the threshold.

### Testing done
Manually tested that agents that were taken offline manually stay offline.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by mawinter69** [comment]
@janasrikanth can you please review

**Comment by janasrikanth** [comment]
Hi @mawinter69 
Let me test it
thanks

**Comment by mawinter69** [comment]
Can you label this PR as bug and then trigger the `cd` action manually so a new release is done

**Pull request merged**
